import streamlit as st
import pandas as pd
from datetime import datetime
import os

st.set_page_config(layout="wide")
st.title("Sports Betting Dashboard")

tabs = st.tabs(["NBA", "MLB", "Bankroll Tracker"])
today = datetime.now().strftime('%Y-%m-%d')

def display_picks(sport, df):
    for i, row in df.iterrows():
        st.subheader(f"{row['away_team']} @ {row['home_team']}")
        st.text(f"Bookmaker: {row['bookmaker']} | Team: {row['team']} | Price: {row['price']}")
        with st.expander("Why this pick?"):
            st.write("Generated by enhanced model with latest stats, injuries, public betting trends, and line movement.")
        if st.button(f"Add ${10} bet on {row['team']}", key=f"{sport}_{i}"):
            st.success(f"Bet on {row['team']} added to bankroll tracker!")

with tabs[0]:
    st.header("NBA Picks")
    nba_path = f"data/processed/nba_features_{today}.csv"
    if os.path.exists(nba_path):
        nba_df = pd.read_csv(nba_path).head(10)
        display_picks("nba", nba_df)
    else:
        st.warning("NBA data not available yet.")

with tabs[1]:
    st.header("MLB Picks")
    mlb_path = f"data/processed/mlb_features_{today}.csv"
    if os.path.exists(mlb_path):
        mlb_df = pd.read_csv(mlb_path).head(10)
        display_picks("mlb", mlb_df)
    else:
        st.warning("MLB data not available yet.")

with tabs[2]:
    st.header("Bankroll Tracker")
    st.write("This section will soon display all tracked bets and ROI.")
